dist: xenial
sudo: false
language: python
python:
    - "3.7"

before_install:
  - nvm install 10.15.1
  - nvm use 10.15.1

install: pip install tox-travis coveralls
script:
    - tox
    - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then coveralls; fi
